services:

    postgres:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: cybo_neutron
        ports:
            - "5435:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/18/data


volumes:
    postgres_data:
      driver: local

