GET http://localhost:3500/v1/movie

###

    # "name": ";\"truncate table \"user\";\"",
###

POST http://localhost:3500/insert_user HTTP/1.1
Content-Type: application/json

{
    "name" : "neer",
    "email": "neer@email.com",
    "password": "password"
}

###

GET http://localhost:3500/get_user?name=neer' OR '1'='1' --  HTTP/1.1
###


GET http://localhost:3500/get_user?name=neer';TRUNCATE TABLE "user" CASCADE; -- HTTP/1.1
###



